#%RAML 1.0
title: Library API (Simple Demo)
version: v1
baseUri: http://localhost:5000
mediaType: application/json

types:
  SuccessResponse:
    type: object
    properties:
      success: boolean
      message: string
      data: any

  ErrorResponse:
    type: object
    properties:
      success: boolean
      error: string

  ApiInfo:
    type: object
    properties:
      name: string
      endpoints: string[]

  HealthData:
    type: object
    properties:
      status: string

  Book:
    type: object
    properties:
      id: integer
      title: string
      author: string

  BookCreateRequest:
    type: object
    properties:
      title: string
      author: string
    required: [title, author]

  BookUpdateRequest:
    type: object
    properties:
      title?: string
      author?: string

/health:
  get:
    responses:
      200:
        body:
          application/json:
            type: SuccessResponse

/books:
  get:
    responses:
      200:
        body:
          application/json:
            type: SuccessResponse
  post:
    body:
      application/json:
        type: BookCreateRequest
    responses:
      201:
        body:
          application/json:
            type: SuccessResponse
      400:
        body:
          application/json:
            type: ErrorResponse

/books/{bookId}:
  uriParameters:
    bookId:
      type: integer
      minimum: 1
  get:
    responses:
      200:
        body:
          application/json:
            type: SuccessResponse
      404:
        body:
          application/json:
            type: ErrorResponse
  put:
    body:
      application/json:
        type: BookUpdateRequest
    responses:
      200:
        body:
          application/json:
            type: SuccessResponse
      404:
        body:
          application/json:
            type: ErrorResponse
  delete:
    responses:
      200:
        body:
          application/json:
            type: SuccessResponse
      404:
        body:
          application/json:
            type: ErrorResponse
